# Repositories section
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: kusionstack
    url: https://kusionstack.github.io/charts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: jetstack
    url: https://charts.jetstack.io

# Releases section
releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.15.0 
    wait: true
    values:
      - installCRDs: true

  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 70.3.0
    values:
      - values/prometheus-values.yaml 

  - name: blackbox-exporter
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/prometheus-blackbox-exporter
    version: 9.4.0
    values:
      - values/blackbox-exporter-values.yaml 
      
  - name: backend-service
    namespace: backend-team
    createNamespace: true
    chart: ./charts/team-service
    needs:
      - monitoring/blackbox-exporter
    values:
      - values/probes-values.yaml
      - values/probes-backend-values.yaml

  - name: frontend-service
    namespace: frontend-team
    createNamespace: true
    chart: ./charts/team-service
    needs:
      - monitoring/blackbox-exporter
    values:
      - values/probes-values.yaml
      - values/probes-frontend-values.yaml

  - name: dashboards
    namespace: monitoring
    createNamespace: true
    chart: ./charts/dashboards
    needs:
      - monitoring/prometheus
    values:
      - values/dashboards-values.yaml

  - name: otel-operator
    namespace: opentelemetry-operator-system
    createNamespace: true
    chart: open-telemetry/opentelemetry-operator
    version: 0.82.2
    needs:
      - cert-manager/cert-manager
    wait: true
    values:
     - values/otel-operator-values.yaml
    hooks:
      - name: apply-otel-collector-manifest
        events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-n", "monitoring", "-f", "manifests/otel-collector.yaml"]

  # - name: karpor
  #   namespace: karpor
  #   createNamespace: true
  #   chart: kusionstack/karpor
  #   values:
  #     - values/karpor-values.yaml
