# Repositories section
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

# Releases section
releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 70.3.0
    values:
      - values/prometheus-values.yaml 

  - name: blackbox-exporter
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/prometheus-blackbox-exporter
    version: 9.4.0
    values:
      - values/blackbox-exporter-values.yaml 
      
  - name: probes
    namespace: monitoring
    createNamespace: true
    chart: ./charts/probes
    needs:
      - monitoring/blackbox-exporter
    values:
      - values/probes-values.yaml
