# Repositories section
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

# Releases section
releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 70.3.0
    values:
      - values/prometheus-values.yaml 
