apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.serviceName }}
  labels:
    app: {{ .Values.nginx.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nginx.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.serviceName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Chart.Name }}-config 
