apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.serviceName }}
  labels:
    app: {{ .Values.nginx.serviceName }}
spec:
  type: ClusterIP  # Using ClusterIP for internal Kubernetes service
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.nginx.serviceName }} 
