apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: sample-service
spec:
  type: ClusterIP  # Using ClusterIP for internal Kubernetes service
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sample-service 
