apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.nginx.serviceName }}-monitor
  labels:
    app: {{ .Values.nginx.serviceName }}
    release: prometheus # This assumes prometheus-operator was installed with release name "prometheus"
spec:
  selector:
    matchLabels:
      app: {{ .Values.nginx.serviceName }}
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
