version: '3.8'

services:
  # Java Application
  app:
    build: .
    container_name: java-app
    ports:
      - "18080:18080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=demo-service
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_JAVAAGENT_DEBUG=false
    depends_on:
      - otel-collector

  # Jaeger for trace visualization
  jaeger:
    image: jaegertracing/all-in-one:1.45.0
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
   

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
    
